// Generated by https://quicktype.io

export interface ListNextProps {
    lastNames: string;
    name:      string;
    dateBirth: DateBirth;
    id:        string;
}

export interface DateBirth {
    seconds:     number;
    nanoseconds: number;
}
